spring:
  application:
    name: hrm-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: POSTGRESQL
jwt:
  expiry-date: 3600
  secret: ${JWT_SECRET}
api-prefix: /api/v1
