name: "[CI] HRM Frontend Build and Test"

on:
  pull_request:
    types: [assigned]
    paths:
      - "hrm-front/**"
      - ".github/workflows/ci-hrm-front.yml"
      - "!hrm-front/.vscode/**"
      - "!hrm-front/*.code-workspace"
jobs:
  ci-check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "22.17.0"
    defaults:
      run:
        working-directory: ./hrm-front
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install npm and Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          # Caching npm dependencies in monorepos
          # https://github.com/actions/setup-node#caching-packages-data
          cache-dependency-path: hrm-front/package-lock.json
      - run: npm ci
      - run: npm run build
