name: "[CI] HRM API Build and Test"

on:
  pull_request:
    types: [assigned]
    paths:
      - "hrm-api/**"
      - ".github/workflows/ci-hrm-api.yml"
      - "!hrm-api/.vscode/**"
      - "!hrm-api/*.code-workspace"
jobs:
  ci-check:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: "21"
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: 5432
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    defaults:
      run:
        working-directory: ./hrm-api
    permissions:
      contents: read
    services:
      postgres-db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK ${{env.JDK_VERSION}}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{env.JDK_VERSION}}
          cache: "maven"
          # Caching npm dependencies in monorepos
          # https://github.com/actions/setup-java#caching-packages-data
          cache-dependency-path: hrm-api/pom.xml
      - run: mvn clean install -DskipTests
      - run: mvn test
