name: "[CI] OpenAPI Typespec Build and Test"

on:
  pull_request:
    types: [assigned]
    paths:
      - "openapi-typespec/**"
      - ".github/workflows/ci-openapi-typespec.yml"
      - "!openapi-typespec/.vscode/**"
      - "!openapi-typespec/*.code-workspace"
jobs:
  ci-check:
    runs-on: [self-hosted, "${{github.event.sender.login}}"]
    env:
      NODE_VERSION: "22.17.0"
    defaults:
      run:
        working-directory: ./openapi-typespec
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install npm and Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          # Caching npm dependencies in monorepos
          # https://github.com/actions/setup-node#caching-packages-data
          cache-dependency-path: hrm-front/package-lock.json

      - name: Install Typespec Compile
        run: npm install -g @typespec/compiler

      - name: Install npm
        run: npm ci

      - name: Generator OpenAPI files
        run: npm run generate
